import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import CountriesDetail from '../components/CountriesDetail';
import Country from '../components/Country';
import Filter from '../components/Filter';
import Header from '../components/Header';
import Search from '../components/Search';
import styles from '../styles/Home.module.css';
import { CountryModel } from '../types/CountryType';

export type PageProps = {
	countries: CountryModel[];
};
const Home = ({ countries }: PageProps) => {
	// const [countryList, setCountryList] = useState<CountryModel[]>([]);
	// setCountryList(countries);
	const [serachTerm, setSearchTerm] = useState<string>('');

	let filteredcountries = countries.filter((country) =>
		country.name.common.toLowerCase().includes('united')
	);

	const handleOnChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		setSearchTerm(e.target.value);
	};
	return (
		<>
			<Head>
				<title>Where in the world</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header />
			{/* <Search /> */}
			<div className='relative my-10 mx-5'>
				<div className='absolute inset-y-0 left-0 flex items-center pl-3'>
					<svg
						xmlns='http://www.w3.org/2000/svg'
						className='h-6 w-6 text-gray-2'
						fill='none'
						viewBox='0 0 24 24'
						stroke='currentColor'
						strokeWidth={2}
					>
						<path
							strokeLinecap='round'
							strokeLinejoin='round'
							d='M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z'
						/>
					</svg>
				</div>
				<input
					onChange={handleOnChange}
					type='search'
					className='block w-full rounded-lg p-4 pl-12 shadow-md outline-none focus:ring-2 focus:ring-blue-3 '
					placeholder='Search for countries...'
				/>
			</div>
			<div className='w-48'>
				<select
					title='SelectRegion'
					className=' mx-5 block max-w-xs rounded-lg py-3 px-4 text-base  text-gray-2 shadow-md outline-none'
				>
					<option value=''>Filter by Region</option>
					<option value='US'>Africa</option>
					<option value='CA'>America</option>
					<option value='FR'>Asia</option>
					<option value='DE'>Europe</option>
					<option value='DE'>Oceania</option>
				</select>
			</div>
			{/* <Filter /> */}
			{filteredcountries.map((country, index) => (
				<div key={index}>
					<Country {...country} />
				</div>
			))}
			{/* <CountriesDetail /> */}
		</>
	);
};

export const getServerSideProps: GetServerSideProps = async (
	pageContext: any
) => {
	const pageNumber = pageContext.query.id;
	const apiUrl = 'http://localhost:3000/data.json';

	const apiResponse = await fetch(apiUrl).then((res) => res.json());
	// console.log(apiResponse);
	const countries: CountryModel[] = apiResponse;
	console.log(countries[1]);
	return {
		props: {
			countries: countries,
		},
	};
};

export default Home;
